// src/pages/HomePage.jsx
import { useState, useEffect, useRef } from "react";
import { EVENTS, HERO_SLIDES } from "../data";
import { EventCard } from "../components";

export function HomePage({ navigate, onEventClick }) {
  const [slide, setSlide] = useState(0);
  const timerRef = useRef(null);

  useEffect(() => {
    timerRef.current = setInterval(() => setSlide(s => (s + 1) % HERO_SLIDES.length), 5000);
    return () => clearInterval(timerRef.current);
  }, []);

  const goSlide = (n) => { setSlide(n); clearInterval(timerRef.current); timerRef.current = setInterval(() => setSlide(s => (s + 1) % HERO_SLIDES.length), 5000); };

  return (
    <div className="page-enter">
      <div className="hero">
        {HERO_SLIDES.map((s, i) => (
          <div key={s.id} className={`hero-slide ${i === slide ? "active" : ""}`} style={{ background: s.bg }}>
            <div className="hero-bg">
              <img src={s.event.image} alt={s.event.title} />
              <div className="hero-gradient" />
            </div>
            <div className="hero-content">
              <div className="hero-badge">
                <span>🔥</span>
                {s.event.category === "concerts" ? "Featured Concert" : s.event.category === "sports" ? "Big Match" : "Featured Show"}
              </div>
              <div className="hero-title">{s.event.title}</div>
              <div className="hero-meta">
                <span className="hero-meta-item"><span>📅</span>{s.event.date}</span>
                <span className="hero-meta-item"><span>📍</span>{s.event.location}</span>
              </div>
              <div className="hero-price">From {s.event.price}</div>
              <div className="hero-actions">
                <button className="btn btn-primary" onClick={() => onEventClick(s.event)}>Book Now</button>
                <button className="btn btn-outline" style={{ borderColor: "rgba(255,255,255,0.2)", color: "#fff" }} onClick={() => onEventClick(s.event)}>View Details</button>
              </div>
            </div>
          </div>
        ))}
        <div className="hero-arrow left" onClick={() => goSlide((slide - 1 + HERO_SLIDES.length) % HERO_SLIDES.length)}>‹</div>
        <div className="hero-arrow right" onClick={() => goSlide((slide + 1) % HERO_SLIDES.length)}>›</div>
        <div className="hero-dots">
          {HERO_SLIDES.map((_, i) => <div key={i} className={`hero-dot ${i === slide ? "active" : ""}`} onClick={() => goSlide(i)} />)}
        </div>
      </div>

      <div className="section">
        <div className="section-header">
          <div className="section-title">🔥 Trending Now <span className="section-badge">Hot</span></div>
          <div className="see-all" onClick={() => navigate("concerts")}>See all →</div>
        </div>
        <div className="scroll-row">
          {[...EVENTS.concerts.slice(0, 3), ...EVENTS.sports.slice(0, 2), ...EVENTS.arts.slice(0, 2)].map(e => (
            <EventCard key={e.id} event={{ ...e, category: e.genre || e.sport || e.type || "Event" }} onClick={onEventClick} />
          ))}
        </div>
      </div>

      <div className="promo-banner promo-1">
        <div>
          <div style={{ fontSize: 12, color: "var(--emerald)", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 8 }}>Limited Time Offer</div>
          <div className="promo-title">Early Bird Deals 🎟️</div>
          <div className="promo-sub">Save up to 40% on selected events. Grab your tickets before they're gone!</div>
          <button className="btn btn-primary" onClick={() => navigate("concerts")}>Browse Deals</button>
        </div>
        <div className="promo-deco">🎵</div>
      </div>

      <div className="section">
        <div className="section-header">
          <div className="section-title">🎵 Concerts</div>
          <div className="see-all" onClick={() => navigate("concerts")}>See all →</div>
        </div>
        <div className="scroll-row">
          {EVENTS.concerts.map(e => <EventCard key={e.id} event={{ ...e, category: e.genre }} onClick={onEventClick} />)}
        </div>
      </div>

      <div className="section">
        <div className="section-header">
          <div className="section-title">⚽ Sports</div>
          <div className="see-all" onClick={() => navigate("sports")}>See all →</div>
        </div>
        <div className="scroll-row">
          {EVENTS.sports.map(e => <EventCard key={e.id} event={{ ...e, category: e.sport }} onClick={onEventClick} />)}
        </div>
      </div>

      <div className="promo-banner promo-2">
        <div>
          <div style={{ fontSize: 12, color: "#A78BFA", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 8 }}>For Organizers</div>
          <div className="promo-title">Host Your Event 🚀</div>
          <div className="promo-sub">Reach millions of event-goers. Set up your event page in minutes with our powerful tools.</div>
          <button className="btn btn-primary" style={{ background: "#7C3AED" }} onClick={() => navigate("organizer")}>Create Event Free</button>
        </div>
        <div className="promo-deco">🎪</div>
      </div>

      <div className="section">
        <div className="section-header">
          <div className="section-title">🎭 Arts & Theatre</div>
          <div className="see-all" onClick={() => navigate("arts")}>See all →</div>
        </div>
        <div className="scroll-row">
          {EVENTS.arts.map(e => <EventCard key={e.id} event={{ ...e, category: e.type }} onClick={onEventClick} />)}
        </div>
      </div>

      <div className="section">
        <div className="section-header">
          <div className="section-title">🧭 Experiences</div>
          <div className="see-all" onClick={() => navigate("experiences")}>See all →</div>
        </div>
        <div className="scroll-row">
          {EVENTS.experiences.map(e => <EventCard key={e.id} event={{ ...e }} onClick={onEventClick} />)}
        </div>
      </div>

      <div className="section">
        <div className="section-header">
          <div className="section-title">📚 Workshops</div>
          <div className="see-all" onClick={() => navigate("workshops")}>See all →</div>
        </div>
        <div className="scroll-row">
          {EVENTS.workshops.map(e => <EventCard key={e.id} event={{ ...e }} onClick={onEventClick} />)}
        </div>
      </div>
    </div>
  );
}

// eventsphere-client/src/pages/HomePage.vue
<template>
  <div class="page-enter">
    <!-- HERO -->
    <div class="hero">
      <div v-for="(s, i) in HERO_SLIDES" :key="s.id" :class="['hero-slide', i === slide ? 'active' : '']" :style="{ background: s.bg }">
        <div class="hero-bg">
          <img :src="s.event.image" :alt="s.event.title" />
          <div class="hero-gradient" />
        </div>
        <div class="hero-content">
          <div class="hero-badge">
            <span>🔥</span>
            {{ s.event.category === 'concerts' ? 'Featured Concert' : s.event.category === 'sports' ? 'Big Match' : 'Featured Show' }}
          </div>
          <div class="hero-title">{{ s.event.title }}</div>
          <div class="hero-meta">
            <span class="hero-meta-item"><span>📅</span>{{ s.event.date }}</span>
            <span class="hero-meta-item"><span>📍</span>{{ s.event.location }}</span>
          </div>
          <div class="hero-price">From {{ s.event.price }}</div>
          <div class="hero-actions">
            <button class="btn btn-primary" @click="goToEvent(s.event)">Book Now</button>
            <button class="btn btn-outline" style="border-color: rgba(255,255,255,0.2); color: #fff" @click="goToEvent(s.event)">View Details</button>
          </div>
        </div>
      </div>
      <div class="hero-arrow left" @click="goSlide((slide - 1 + HERO_SLIDES.length) % HERO_SLIDES.length)">‹</div>
      <div class="hero-arrow right" @click="goSlide((slide + 1) % HERO_SLIDES.length)">›</div>
      <div class="hero-dots">
        <div v-for="(_, i) in HERO_SLIDES" :key="i" :class="['hero-dot', i === slide ? 'active' : '']" @click="goSlide(i)" />
      </div>
    </div>

    <!-- Trending -->
    <div class="section">
      <div class="section-header">
        <div class="section-title">🔥 Trending Now <span class="section-badge">Hot</span></div>
        <router-link to="/concerts" class="see-all">See all →</router-link>
      </div>
      <div class="scroll-row">
        <EventCard v-for="e in trending" :key="e.id" :event="e" />
      </div>
    </div>

    <!-- Promo 1 -->
    <div class="promo-banner promo-1">
      <div>
        <div style="font-size: 12px; color: var(--emerald); font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 8px">Limited Time Offer</div>
        <div class="promo-title">Early Bird Deals 🎟️</div>
        <div class="promo-sub">Save up to 40% on selected events. Grab your tickets before they're gone!</div>
        <router-link to="/concerts" class="btn btn-primary">Browse Deals</router-link>
      </div>
      <div class="promo-deco">🎵</div>
    </div>

    <!-- Category sections -->
    <div v-for="cat in categories" :key="cat.key" class="section">
      <div class="section-header">
        <div class="section-title">{{ cat.icon }} {{ cat.label }}</div>
        <router-link :to="'/' + cat.key" class="see-all">See all →</router-link>
      </div>
      <div class="scroll-row">
        <EventCard v-for="e in cat.items" :key="e.id" :event="e" />
      </div>
      <!-- Promo 2 after sports -->
      <div v-if="cat.key === 'sports'" class="promo-banner promo-2" style="margin-top: 52px">
        <div>
          <div style="font-size: 12px; color: #A78BFA; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 8px">For Organizers</div>
          <div class="promo-title">Host Your Event 🚀</div>
          <div class="promo-sub">Reach millions of event-goers. Set up your event page in minutes with our powerful tools.</div>
          <router-link to="/organizer" class="btn btn-primary" style="background: #7C3AED">Create Event Free</router-link>
        </div>
        <div class="promo-deco">🎪</div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted, computed } from 'vue'
import { useRouter } from 'vue-router'
import { EVENTS, HERO_SLIDES } from '../data'
import { selectEvent } from '../stores/eventStore'
import EventCard from '../components/EventCard.vue'

const router = useRouter()

const slide = ref(0)
let timer = null

const goSlide = (n) => {
  slide.value = n
  clearInterval(timer)
  timer = setInterval(() => { slide.value = (slide.value + 1) % HERO_SLIDES.length }, 5000)
}

const goToEvent = (event) => {
  selectEvent(event)
  router.push('/event/' + event.id)
}

onMounted(() => { timer = setInterval(() => { slide.value = (slide.value + 1) % HERO_SLIDES.length }, 5000) })
onUnmounted(() => clearInterval(timer))

const trending = computed(() => [
  ...EVENTS.concerts.slice(0, 3).map(e => ({ ...e, category: e.genre })),
  ...EVENTS.sports.slice(0, 2).map(e => ({ ...e, category: e.sport })),
  ...EVENTS.arts.slice(0, 2).map(e => ({ ...e, category: e.type })),
])

const categories = computed(() => [
  { key: 'concerts', icon: '🎵', label: 'Concerts', items: EVENTS.concerts.map(e => ({ ...e, category: e.genre })) },
  { key: 'sports', icon: '⚽', label: 'Sports', items: EVENTS.sports.map(e => ({ ...e, category: e.sport })) },
  { key: 'arts', icon: '🎭', label: 'Arts & Theatre', items: EVENTS.arts.map(e => ({ ...e, category: e.type })) },
  { key: 'experiences', icon: '🧭', label: 'Experiences', items: EVENTS.experiences },
  { key: 'workshops', icon: '📚', label: 'Workshops', items: EVENTS.workshops },
])
</script>
